language: node_js
node_js:
  - 8.17.0
  - 10
  - 12
  - 14
cache: npm
install:
  - npm install -g yarn@`cat package.json | jq -r '.engines.yarn // "^1.2.1"'`
  - 'npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN'
  - 'npm config set @coorpacademy:registry http://registry.npmjs.org/'
script:
  - npm test
after_script:
   npm run codecov
